const Sample = require('../../database/models/Sample');
const User = require('../../database/models/User');
const Customer = require('../../database/models/Customer');
const Product = require('../../database/models/Product');

// @desc    Get all samples
// @route   GET /api/admin/samples
// @access  Private/Admin
const getSamples = async (req, res) => {
  try {
    const { salesman, status, search, startDate, endDate } = req.query;
    const filter = {};

    if (salesman) {
      filter.salesman = salesman;
    }
    if (status) {
      filter.status = status;
    }
    if (search) {
      filter.$or = [
        { sampleNumber: { $regex: search, $options: 'i' } },
        { customerName: { $regex: search, $options: 'i' } },
        { customerEmail: { $regex: search, $options: 'i' } },
        { productName: { $regex: search, $options: 'i' } },
        { productCode: { $regex: search, $options: 'i' } },
      ];
    }
    if (startDate || endDate) {
      filter.visitDate = {};
      if (startDate) {
        filter.visitDate.$gte = new Date(startDate);
      }
      if (endDate) {
        filter.visitDate.$lte = new Date(endDate);
      }
    }

    const samples = await Sample.find(filter)
      .populate('salesman', 'name email')
      .populate('customer', 'name email phone')
      .populate('product', 'name productCode price')
      .populate('visitTarget', 'name address')
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: samples.length,
      data: samples,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Error fetching samples',
    });
  }
};

// @desc    Create sample
// @route   POST /api/admin/samples
// @access  Private/Admin
const createSample = async (req, res) => {
  try {
    const {
      salesman,
      customer,
      customerName,
      customerEmail,
      customerPhone,
      product,
      productName,
      productCode,
      quantity,
      visitTarget,
      visitDate,
      expectedDate,
      notes,
    } = req.body;

    // Validate required fields
    if (!salesman) {
      return res.status(400).json({
        success: false,
        message: 'Please provide salesman',
      });
    }

    if (!customerName) {
      return res.status(400).json({
        success: false,
        message: 'Please provide customer name',
      });
    }

    if (!productName) {
      return res.status(400).json({
        success: false,
        message: 'Please provide product name',
      });
    }

    // Verify salesman exists
    const salesmanUser = await User.findById(salesman);
    if (!salesmanUser || salesmanUser.role !== 'salesman') {
      return res.status(400).json({
        success: false,
        message: 'Invalid salesman selected',
      });
    }

    // Verify customer exists if provided
    if (customer) {
      const customerDoc = await Customer.findById(customer);
      if (!customerDoc) {
        return res.status(400).json({
          success: false,
          message: 'Customer not found',
        });
      }
    }

    // Verify product exists if provided
    if (product) {
      const productDoc = await Product.findById(product);
      if (!productDoc || !productDoc.isActive) {
        return res.status(400).json({
          success: false,
          message: 'Product not found or inactive',
        });
      }
    }

    // Create sample (sampleNumber will be auto-generated by pre-save hook)
    const sample = await Sample.create({
      salesman,
      customer: customer || undefined,
      customerName,
      customerEmail: customerEmail || undefined,
      customerPhone: customerPhone || undefined,
      product: product || undefined,
      productName,
      productCode: productCode || undefined,
      quantity: quantity || 1,
      visitTarget: visitTarget || undefined,
      visitDate: visitDate ? new Date(visitDate) : new Date(),
      expectedDate: expectedDate ? new Date(expectedDate) : undefined,
      notes: notes || undefined,
      status: 'Pending',
      createdBy: req.user._id,
    });

    const populatedSample = await Sample.findById(sample._id)
      .populate('salesman', 'name email')
      .populate('customer', 'name email phone')
      .populate('product', 'name productCode price')
      .populate('visitTarget', 'name address');

    res.status(201).json({
      success: true,
      message: 'Sample created successfully',
      data: populatedSample,
    });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({
        success: false,
        message: 'Sample number already exists',
      });
    }
    res.status(500).json({
      success: false,
      message: error.message || 'Error creating sample',
    });
  }
};

// @desc    Get single sample
// @route   GET /api/admin/samples/:id
// @access  Private/Admin
const getSample = async (req, res) => {
  try {
    const sample = await Sample.findById(req.params.id)
      .populate('salesman', 'name email phone')
      .populate('customer', 'name email phone address')
      .populate('product', 'name productCode price description')
      .populate('visitTarget', 'name address city');

    if (!sample) {
      return res.status(404).json({
        success: false,
        message: 'Sample not found',
      });
    }

    res.status(200).json({
      success: true,
      data: sample,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Error fetching sample',
    });
  }
};

// @desc    Update sample
// @route   PUT /api/admin/samples/:id
// @access  Private/Admin
const updateSample = async (req, res) => {
  try {
    const { status, customerFeedback, notes, receivedDate, convertedDate } = req.body;

    const sample = await Sample.findById(req.params.id);
    if (!sample) {
      return res.status(404).json({
        success: false,
        message: 'Sample not found',
      });
    }

    if (status) {
      sample.status = status;
      if (status === 'Received' && !sample.receivedDate) {
        sample.receivedDate = receivedDate || new Date();
      }
      if (status === 'Converted' && !sample.convertedDate) {
        sample.convertedDate = convertedDate || new Date();
      }
    }
    if (customerFeedback !== undefined) {
      sample.customerFeedback = customerFeedback;
    }
    if (notes !== undefined) {
      sample.notes = notes;
    }

    await sample.save();

    const populatedSample = await Sample.findById(sample._id)
      .populate('salesman', 'name email')
      .populate('customer', 'name email phone')
      .populate('product', 'name productCode price')
      .populate('visitTarget', 'name address');

    res.status(200).json({
      success: true,
      message: 'Sample updated successfully',
      data: populatedSample,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Error updating sample',
    });
  }
};

// @desc    Delete sample
// @route   DELETE /api/admin/samples/:id
// @access  Private/Admin
const deleteSample = async (req, res) => {
  try {
    const sample = await Sample.findById(req.params.id);
    if (!sample) {
      return res.status(404).json({
        success: false,
        message: 'Sample not found',
      });
    }

    await Sample.findByIdAndDelete(req.params.id);

    res.status(200).json({
      success: true,
      message: 'Sample deleted successfully',
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Error deleting sample',
    });
  }
};

// @desc    Get sample statistics
// @route   GET /api/admin/samples/stats
// @access  Private/Admin
const getSampleStats = async (req, res) => {
  try {
    const totalSamples = await Sample.countDocuments();
    const pendingSamples = await Sample.countDocuments({ status: 'Pending' });
    const receivedSamples = await Sample.countDocuments({ status: 'Received' });
    const convertedSamples = await Sample.countDocuments({ status: 'Converted' });

    res.status(200).json({
      success: true,
      data: {
        total: totalSamples,
        pending: pendingSamples,
        received: receivedSamples,
        converted: convertedSamples,
      },
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message || 'Error fetching sample statistics',
    });
  }
};

module.exports = {
  getSamples,
  getSample,
  createSample,
  updateSample,
  deleteSample,
  getSampleStats,
};
